# Generated by Django 4.2.13 on 2024-07-01 10:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('superviseur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gouvernorat_libelle', models.CharField(blank=True, max_length=255, null=True)),
                ('delegation_libelle', models.CharField(blank=True, max_length=255, null=True)),
                ('localite_libelle', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'unique_together': {('gouvernorat_libelle', 'delegation_libelle', 'localite_libelle')},
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('geomp', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('descp', models.TextField(null=True)),
                ('date_debut', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_fin', models.DateTimeField()),
                ('piece_joindre', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('polygon_id', models.BigAutoField(default=None, primary_key=True, serialize=False)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='superviseur.localisation')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
        ),
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcelle', to='superviseur.project')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('position', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('reference', models.CharField(max_length=50, null=True)),
                ('node_range', models.BigIntegerField(blank=True, null=True)),
                ('sensors', models.CharField(max_length=50, null=True)),
                ('RSSI', models.BigIntegerField(null=True)),
                ('Battery_value', models.BigIntegerField(null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('FWI', models.FloatField(default=0, null=True)),
                ('detection', models.BigIntegerField(null=True)),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='superviseur.parcelle')),
            ],
        ),
    ]
