# Generated by Django 4.2.13 on 2024-08-19 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superviseur', '0002_localisation_project_parcelle_node'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('idData', models.AutoField(primary_key=True, serialize=False)),
                ('temperature', models.BigIntegerField(null=True)),
                ('humidity', models.BigIntegerField(null=True)),
                ('pressur', models.BigIntegerField(null=True)),
                ('gaz', models.BigIntegerField(null=True)),
                ('detection', models.BigIntegerField(null=True)),
                ('wind', models.FloatField(default=0, null=True)),
                ('rain', models.FloatField(default=0, null=True)),
                ('ffmc', models.FloatField(null=True)),
                ('isi', models.FloatField(null=True)),
                ('fwi', models.FloatField(null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='superviseur.node')),
            ],
        ),
    ]
